"""Application-wide defaults and metadata."""

DEFAULT_BALANCE = 10_000.0
DEFAULT_RISK_PCT = 1.0
DEFAULT_STOP_LOSS_PIPS = 25.0
DEFAULT_TAKE_PROFIT_PIPS = 50.0
DEFAULT_PIP_VALUE_PER_LOT = 10.0

APP_NAME = "Forex Money Manager"
APP_VERSION = "1.1.0"
